# Generated by Django 4.0.4 on 2022-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
                ('st_id', models.IntegerField()),
                ('st_phone', models.CharField(max_length=13)),
                ('st_email', models.CharField(max_length=100)),
                ('st_birthdate', models.DateField()),
                ('st_gender', models.CharField(max_length=6)),
                ('st_level', models.IntegerField()),
                ('st_department', models.CharField(max_length=2)),
                ('st_active', models.BooleanField(default=True)),
            ],
        ),
    ]
