# Generated by Django 4.0.4 on 2022-05-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_id',
            field=models.CharField(max_length=8),
        ),
    ]
