# Generated by Django 4.0.4 on 2022-05-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0002_alter_student_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_department',
            field=models.CharField(max_length=6),
        ),
    ]
