# Generated by Django 4.0.4 on 2022-05-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0003_alter_student_st_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='st_gpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
