# Generated by Django 4.0.4 on 2022-05-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0007_alter_student_st_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_email',
            field=models.EmailField(max_length=100),
        ),
    ]
