# Generated by Django 4.0.4 on 2022-05-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0008_alter_student_st_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='st_active',
        ),
    ]
