# Generated by Django 4.0.4 on 2022-05-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0010_alter_student_st_birthdate_alter_student_st_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='st_active',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='General', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Table.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
